spring.application.name=task-manager-auth

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/task_db?options=-c%20timezone=UTC
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver


# Otras configuraciones útiles
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
